-- ============================================
-- FUNDING PROGRAMS IMPORT - MATCHED TO YOUR TABLE
-- ============================================
-- Imports 80+ funding programs into YOUR exact table structure
-- ============================================

-- Clear existing data
TRUNCATE TABLE funding_programs CASCADE;

-- ============================================
-- EUROPEAN LEVEL PROGRAMS (3)
-- ============================================

INSERT INTO funding_programs (
    name, provider, country, level, eligible_themes, eligible_population_bands, eligible_regions,
    funding_type, amount_min, amount_max, funding_percentage_min, funding_percentage_max,
    description, website_url, application_url, deadline_type, requirements, required_documents, is_active
) VALUES

('LEADER/FEADER - Développement Rural', 'Commission Européenne / Ministère Agriculture', 'FR', 'European',
ARRAY['agriculture', 'tourism', 'heritage', 'environment', 'economy', 'innovation'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000', '20000-50000', '>50000'],
ARRAY['All regions'],
'grant', 20000, 150000, 50, 80,
'Programme LEADER (Liaison entre Actions de Développement de l''Économie Rurale) financé par le FEADER. Soutient des projets ruraux multi-sectoriels développés par les territoires eux-mêmes. 339 territoires LEADER en France, chaque GAL (Groupe d''Action Locale) dispose d''une enveloppe >1M€ pour 2023-2027.',
'https://leaderfrance.fr', 'https://leader.aides-territoires.beta.gouv.fr', 'rolling',
'Population 10 000-100 000 habitants par GAL. Projet inscrit dans stratégie locale de développement. Co-financement local requis.',
'Dossier LEADER complet, budget prévisionnel détaillé, délibération commune/EPCI, devis, justificatifs co-financement',
true),

('FEADER - Innovation Rurale', 'Commission Européenne / Région', 'FR', 'European',
ARRAY['agriculture', 'innovation', 'economy', 'environment'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000'],
ARRAY['Nouvelle-Aquitaine'],
'grant', 50000, 200000, 40, 80,
'Fonds Européen Agricole pour le Développement Rural (FEADER) axé sur l''innovation. Soutient la compétitivité agricole, la diversification économique, la gestion durable des ressources. Nouvelle-Aquitaine : 193,8M€ FEADER 2023-2027.',
'https://europe-en-france.gouv.fr', 'https://les-aides.nouvelle-aquitaine.fr', 'annual',
'Communes rurales et EPCI. Projet innovant agriculture/ruralité. Co-financement minimum 20-60% selon projet.',
'Formulaire FEADER, plan d''entreprise agricole, études techniques, budget détaillé, décisions collectivités',
true),

('FEDER - Développement Régional', 'Commission Européenne / Région', 'FR', 'European',
ARRAY['infrastructure', 'innovation', 'economy', 'energy', 'digital'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000', '20000-50000', '>50000'],
ARRAY['Nouvelle-Aquitaine'],
'grant', 50000, 500000, 40, 70,
'Fonds Européen de Développement Régional (FEDER). France : 8,4Mds€ 2021-2027. Soutient infrastructures, innovation, transition énergétique, numérique. Projets structurants territoriaux.',
'https://europe-en-france.gouv.fr', 'https://www.demarches-simplifiees.fr', 'rolling',
'Collectivités et EPCI. Projet structurant territorial. APD (Avant-Projet Définitif) requis pour bâtiments >50k€.',
'Dossier FEDER complet, études techniques, devis, délibération, plan de financement, APD si bâtiment',
true);

-- ============================================
-- FRENCH NATIONAL PROGRAMS (35)
-- ============================================

INSERT INTO funding_programs (
    name, provider, country, level, eligible_themes, eligible_population_bands, eligible_regions,
    funding_type, amount_min, amount_max, funding_percentage_min, funding_percentage_max,
    description, website_url, application_url, deadline_type, requirements, required_documents, is_active
) VALUES

-- Infrastructure & Equipment
('DETR - Dotation Équipement Territoires Ruraux', 'Ministère Intérieur / Préfecture', 'FR', 'National',
ARRAY['infrastructure', 'accessibility', 'economy', 'environment'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000'],
ARRAY['All regions'],
'grant', 10000, 200000, 20, 80,
'Dotation d''Équipement des Territoires Ruraux. Communes <20 000 hab avec faible potentiel fiscal (<1 222€/hab). Minimum 10k€ HT. Commission DETR départementale fixe taux 20-80%.',
'https://www.collectivites-locales.gouv.fr', 'https://www.demarches-simplifiees.fr', 'annual',
'Communes <20k hab, potentiel fiscal <1 222€/hab. Dépôt annuel Oct-Déc. Projet d''investissement. Non cumulable avec DRAC MH.',
'Délibération conseil municipal, devis, APD si bâtiment, plan de financement, certificats urbanisme si construction',
true),

('DSIL - Dotation Soutien Investissement Local', 'Ministère Intérieur / Préfecture', 'FR', 'National',
ARRAY['infrastructure', 'energy', 'economy', 'accessibility', 'mobility'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000', '20000-50000', '>50000'],
ARRAY['All regions'],
'grant', 100000, 1000000, 40, 60,
'Dotation de Soutien à l''Investissement Local. Toutes communes et EPCI éligibles. Projets >50k€, maturité avancée (APD). Priorités : rénovation thermique, transition écologique.',
'https://www.collectivites-locales.gouv.fr', 'https://www.demarches-simplifiees.fr', 'annual',
'Toutes communes et EPCI. Projet >50k€, APD requis. Maturité du projet essentielle.',
'Délibération, APD complet, devis, plan financement détaillé, certificats conformité urbanisme',
true),

('FIPD - Fonds Interministériel Prévention Délinquance', 'CIPDR / Préfecture', 'FR', 'National',
ARRAY['security', 'social', 'youth'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000', '20000-50000', '>50000'],
ARRAY['All regions'],
'grant', 10000, 50000, 40, 70,
'Fonds Interministériel de Prévention de la Délinquance. Vidéosurveillance, éclairage public, prévention jeunesse. Conformité RGPD obligatoire pour vidéo.',
'https://www.cipdr.gouv.fr', 'https://www.demarches-simplifiees.fr', 'annual',
'Communes et EPCI. Stratégie locale sécurité prévention délinquance. Conformité RGPD pour vidéo.',
'Délibération, devis détaillés, dossier vidéoprotection si applicable, évaluation RGPD, stratégie prévention locale',
true),

('Fonds Vert - Accélération Transition Écologique', 'Ministère Transition Écologique / ADEME', 'FR', 'National',
ARRAY['energy', 'climate', 'biodiversity', 'water', 'waste'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000', '20000-50000', '>50000'],
ARRAY['All regions'],
'grant', 50000, 500000, 50, 80,
'Fonds d''accélération de la transition écologique des territoires. 2Mds€/an. Rénovation énergétique, adaptation climatique, biodiversité, gestion eau, économie circulaire.',
'https://www.ecologie.gouv.fr/fonds-vert', 'https://www.demarches-simplifiees.fr', 'rolling',
'Toutes communes et EPCI. Priorité communes <20k hab. Projet transition écologique.',
'Délibération, diagnostic énergétique/écologique, devis, plan action transition écologique, APD si rénovation bâtiment',
true),

-- Cultural Heritage
('DRAC - Patrimoine Classé MH', 'Ministère Culture / DRAC', 'FR', 'National',
ARRAY['heritage', 'culture', 'tourism'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000', '20000-50000', '>50000'],
ARRAY['All regions'],
'grant', 15000, 300000, 35, 80,
'Direction Régionale des Affaires Culturelles - Monuments Historiques classés. Taux moyen 35-50%, jusqu''à 80% pour communes <10k hab via FIP. 2020 : 201M€ engagés, 6 300 opérations.',
'https://www.culture.gouv.fr', 'https://www.demarches-simplifiees.fr', 'rolling',
'Monument Historique classé. Travaux non commencés. Architecte du patrimoine ou ABF. Auto-financement ≥20%.',
'Délibération, devis architecte patrimoine, diagnostic sanitaire monument, programme travaux détaillé, autorisations ABF/DRAC',
true),

('DRAC - Patrimoine Inscrit MH', 'Ministère Culture / DRAC', 'FR', 'National',
ARRAY['heritage', 'culture', 'tourism'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000', '20000-50000', '>50000'],
ARRAY['All regions'],
'grant', 10000, 150000, 15, 40,
'DRAC - Monuments Historiques inscrits. Taux moyen 15-30%, plafonné à 40% dépense effective. Cumulable avec aides régionales/départementales dans limite 80%.',
'https://www.culture.gouv.fr', 'https://www.demarches-simplifiees.fr', 'rolling',
'Monument Historique inscrit. Architecte qualifié. Respect contraintes patrimoniales. Travaux non commencés.',
'Délibération, devis architecte, diagnostic bâtiment, programme travaux, plan financement, autorisation ABF/DRAC si requis',
true),

('Fondation du Patrimoine - Label et Subvention', 'Fondation du Patrimoine', 'FR', 'National',
ARRAY['heritage', 'culture', 'tourism'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000'],
ARRAY['All regions'],
'grant', 5000, 50000, 20, 50,
'Label patrimoine permettant déduction fiscale (50-100%) et/ou subvention directe (minimum 1% TTC). Ouverture publique obligatoire Journées Patrimoine (3 ans).',
'https://www.fondation-patrimoine.org', 'https://www.fondation-patrimoine.org/les-projets', 'rolling',
'Édifice patrimonial non protégé MH. Ouverture au public Journées Patrimoine pendant 3 ans.',
'Dossier fondation (formulaire), photos bâtiment, descriptif historique/architectural, devis travaux, engagement ouverture publique',
true),

-- Environment & Water
('Agence de l''Eau Adour-Garonne', 'Agence de l''Eau Adour-Garonne', 'FR', 'National',
ARRAY['water', 'environment', 'biodiversity'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000', '20000-50000', '>50000'],
ARRAY['Nouvelle-Aquitaine', 'Occitanie'],
'grant', 10000, 100000, 30, 60,
'Gestion de l''eau, milieux aquatiques, biodiversité, assainissement, irrigation. Bassin Adour-Garonne couvrant Nouvelle-Aquitaine.',
'https://agence.eau-adour-garonne.fr', 'https://agence.eau-adour-garonne.fr/aides', 'rolling',
'Communes et EPCI bassin Adour-Garonne. Projet eau/milieux aquatiques.',
'Formulaire agence eau, étude technique eau, devis, délibération, diagnostic milieu aquatique si applicable',
true),

('ADEME - Transition Énergétique', 'ADEME', 'FR', 'National',
ARRAY['energy', 'climate', 'economy'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000', '20000-50000', '>50000'],
ARRAY['All regions'],
'grant', 20000, 150000, 40, 70,
'Projets transition énergétique : audit, rénovation thermique, énergies renouvelables, mobilité propre. Fonds Chaleur et Fonds Air. CRTE.',
'https://www.ademe.fr', 'https://agirpourlatransition.ademe.fr', 'rolling',
'Collectivités et EPCI. Projet transition énergétique. Audit énergétique ou diagnostic requis.',
'Formulaire ADEME, audit énergétique, devis détaillé, plan financement, délibération, engagement résultats',
true),

('ADEME - Économie Circulaire', 'ADEME', 'FR', 'National',
ARRAY['waste', 'environment', 'economy'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000', '20000-50000', '>50000'],
ARRAY['All regions'],
'grant', 15000, 80000, 40, 60,
'Réduction déchets, réemploi, recyclage, compostage collectif. Zéro déchet, anti-gaspillage, SERD. Économie circulaire territoriale.',
'https://www.ademe.fr', 'https://agirpourlatransition.ademe.fr', 'rolling',
'Collectivités et EPCI. Projet économie circulaire/déchets. Diagnostic déchets.',
'Formulaire ADEME, diagnostic déchets, plan action réduction, devis, délibération, indicateurs suivi',
true),

('Office Français Biodiversité (OFB)', 'Office Français de la Biodiversité', 'FR', 'National',
ARRAY['biodiversity', 'environment', 'water'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000', '20000-50000', '>50000'],
ARRAY['All regions'],
'grant', 10000, 80000, 50, 80,
'Espèces et milieux naturels protégés, zones humides, cours d''eau, Natura 2000. Protection et restauration biodiversité.',
'https://www.ofb.gouv.fr', 'https://www.ofb.gouv.fr/subventions', 'rolling',
'Collectivités et EPCI. Projet biodiversité/milieux naturels. Diagnostic écologique.',
'Formulaire OFB, diagnostic écologique, plan gestion milieux naturels, devis, délibération, cartographie zones',
true),

('Mission Haies Agroforesterie', 'Ministère Agriculture / OFB', 'FR', 'National',
ARRAY['agriculture', 'biodiversity', 'environment', 'climate'],
ARRAY['<2000', '2000-5000', '5000-10000'],
ARRAY['All regions'],
'grant', 5000, 30000, 50, 80,
'Plantation et gestion durable haies bocagères, agroforesterie. Trame verte et bleue. Lutte érosion, biodiversité, stockage carbone.',
'https://www.mission-haies.fr', 'https://www.mission-haies.fr/aides', 'annual',
'Communes rurales et agriculteurs. Projet haies/agroforesterie cohérent. Essences locales.',
'Plan plantation haies, devis pépiniériste, cartographie parcellaire, engagement gestion durable, délibération si commune',
true),

-- Digital & Innovation
('France Num - Transformation Numérique', 'DGE / France Num', 'FR', 'National',
ARRAY['digital', 'economy', 'services'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000', '20000-50000', '>50000'],
ARRAY['All regions'],
'grant', 20000, 80000, 40, 60,
'Transformation numérique : outils, formation, infrastructures, tiers-lieux, wifi public. Programme France Num.',
'https://www.francenum.gouv.fr', 'https://www.demarches-simplifiees.fr', 'rolling',
'Collectivités et EPCI. Projet transformation numérique territoire.',
'Formulaire France Num, diagnostic numérique, plan déploiement, devis, délibération, convention tiers-lieu si applicable',
true),

('BPI France - Innovation Territoriale', 'BPI France', 'FR', 'National',
ARRAY['innovation', 'economy', 'digital'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000', '20000-50000', '>50000'],
ARRAY['All regions'],
'grant', 30000, 200000, 30, 50,
'Projets territoriaux innovants : tiers-lieux, fablabs, incubateurs, startups rurales. Soutien écosystème innovation local.',
'https://www.bpifrance.fr', 'https://www.bpifrance.fr/nos-solutions', 'rolling',
'Collectivités, EPCI, structures innovation. Projet innovation territoriale. Modèle économique viable.',
'Business plan innovation, étude marché, devis, partenariats locaux, délibération, engagement porteurs projet',
true),

-- Tourism
('Atout France - Tourisme Durable', 'Atout France', 'FR', 'National',
ARRAY['tourism', 'heritage', 'environment'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000', '20000-50000', '>50000'],
ARRAY['All regions'],
'grant', 20000, 100000, 40, 60,
'Tourisme durable, valorisation patrimoine naturel/culturel, labels qualité. Accompagnement stratégie touristique.',
'https://www.atout-france.fr', 'https://www.atout-france.fr/services/financement', 'annual',
'Collectivités et offices tourisme. Projet tourisme durable. Stratégie territoriale claire.',
'Dossier Atout France, stratégie touristique, étude fréquentation, devis, délibération, plan marketing',
true),

('Destinations France - Ingénierie Touristique', 'Destinations France / Banque Territoires', 'FR', 'National',
ARRAY['tourism', 'heritage', 'economy'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000', '20000-50000', '>50000'],
ARRAY['All regions'],
'grant', 30000, 150000, 40, 50,
'Structuration touristique, parcours découverte, signalétique, valorisation patrimoine. Destinations France.',
'https://www.banquedesterritoires.fr', 'https://www.banquedesterritoires.fr/tourisme', 'rolling',
'Collectivités et EPCI. Projet structuration offre touristique. Parcours cohérent identifié.',
'Schéma touristique territorial, étude fréquentation/retombées, devis, délibération, plan signalétique',
true),

-- Social & Housing
('ANAH - Rénovation Habitat Centre-Bourg', 'ANAH', 'FR', 'National',
ARRAY['housing', 'urban_planning', 'energy'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000'],
ARRAY['All regions'],
'grant', 30000, 120000, 35, 50,
'Rénovation habitat ancien centres-bourgs, réduction vacance, performance énergétique. Propriétaires occupants et bailleurs.',
'https://www.anah.fr', 'https://monprojet.anah.gouv.fr', 'rolling',
'Propriétaires occupants (ressources) ou bailleurs. Logement >15 ans. Centre-bourg identifié.',
'Formulaire ANAH, diagnostic énergétique, devis travaux, conditions ressources, engagement location si bailleur',
true),

('Action Cœur de Ville', 'ANCT / Banque des Territoires', 'FR', 'National',
ARRAY['urban_planning', 'housing', 'commerce', 'heritage'],
ARRAY['10000-20000', '20000-50000'],
ARRAY['All regions'],
'grant', 50000, 300000, 40, 60,
'Revitalisation centres villes moyennes, 234 villes labellisées. Logement, commerce, services, patrimoine. Programme 2018-2026.',
'https://www.anct.gouv.fr/action-coeur-de-ville', 'https://www.demarches-simplifiees.fr', 'rolling',
'Villes labellisées Action Cœur de Ville. Convention signée avec État.',
'Projet détaillé intégré stratégie ACV, devis, plan financement multi-partenaires, délibération, chef projet identifié',
true),

('Petites Villes de Demain', 'ANCT / Banque des Territoires', 'FR', 'National',
ARRAY['urban_planning', 'housing', 'commerce', 'services'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000'],
ARRAY['All regions'],
'grant', 50000, 500000, 50, 80,
'Revitalisation centres petites villes <20k hab, 1 644 communes bénéficiaires. Chef de projet mutualisé.',
'https://www.anct.gouv.fr/petites-villes-de-demain', 'https://www.demarches-simplifiees.fr', 'rolling',
'Communes <20k hab labellisées Petites Villes de Demain. Convention État signée.',
'Projet détaillé PVD, devis, plan financement, délibération, convention signée État, poste chef projet créé',
true),

('CAF - Équipements Enfance Jeunesse', 'CAF', 'FR', 'National',
ARRAY['social', 'youth', 'education'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000', '20000-50000', '>50000'],
ARRAY['All regions'],
'grant', 20000, 100000, 40, 60,
'Équipements petite enfance : crèches, RAM, haltes-garderies. Accueils périscolaires et centres loisirs.',
'https://www.caf.fr', 'https://www.caf.fr/partenaires', 'annual',
'Communes et EPCI. Équipement enfance/jeunesse. Personnel qualifié.',
'Dossier CAF, projet éducatif, devis, plan financement, délibération, agrément PMI si crèche',
true),

-- Culture
('DRAC - Lecture Publique & Bibliothèques', 'Ministère Culture / DRAC', 'FR', 'National',
ARRAY['culture', 'education', 'services'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000', '20000-50000', '>50000'],
ARRAY['All regions'],
'grant', 10000, 50000, 30, 50,
'Bibliothèques, médiathèques, points lecture. Construction, rénovation, équipements, fonds documentaires.',
'https://www.culture.gouv.fr', 'https://www.demarches-simplifiees.fr', 'rolling',
'Communes et EPCI. Projet bibliothèque/médiathèque. Personnel qualifié ou bénévoles formés.',
'Dossier DRAC lecture publique, projet établissement, devis, plan, délibération, descriptif collections',
true),

('CNM - Musiques Actuelles', 'Centre National de la Musique', 'FR', 'National',
ARRAY['culture', 'youth', 'economy'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000', '20000-50000', '>50000'],
ARRAY['All regions'],
'grant', 10000, 60000, 40, 60,
'Lieux musiques actuelles : salles concert, studios répétition. SMAC (Scènes Musiques Actuelles Conventionnées).',
'https://cnm.fr', 'https://cnm.fr/aides-et-services', 'rolling',
'Collectivités et associations. Projet musiques actuelles. Programmation artistique diversifiée.',
'Projet artistique et culturel, budget prévisionnel, devis, délibération, normes acoustiques, licence spectacles',
true),

('CNC - Salles Cinéma Rurales', 'Centre National du Cinéma', 'FR', 'National',
ARRAY['culture', 'economy', 'rural'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000'],
ARRAY['All regions'],
'grant', 30000, 150000, 40, 70,
'Soutien cinéma rural, numérisation, rénovation, accessibilité. Cinémas itinérants, animations jeunesse.',
'https://www.cnc.fr', 'https://www.cnc.fr/professionnels/aides-et-financements', 'annual',
'Communes rurales et associations. Salle cinéma existante ou création.',
'Dossier CNC, projet culturel salle, devis équipements, plan financement, délibération, programmation artistique',
true),

-- Sports
('ANS - Équipements Sportifs Proximité', 'Agence Nationale du Sport', 'FR', 'National',
ARRAY['sports', 'youth', 'infrastructure'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000', '20000-50000', '>50000'],
ARRAY['All regions'],
'grant', 20000, 150000, 30, 50,
'Équipements sportifs proximité : city-stades, terrains multisports, vestiaires. Accessibilité PMR. Héritage JO Paris 2024.',
'https://www.agencedusport.fr', 'https://www.agencedusport.fr/aides', 'rolling',
'Communes et EPCI. Équipement sportif proximité. Normes fédérales. Accessibilité PMR.',
'Projet sportif territorial, devis, plan implantation, délibération, norme accessibilité, convention usage',
true),

('ANS - Projets Sportifs Territoriaux (PST)', 'Agence Nationale du Sport', 'FR', 'National',
ARRAY['sports', 'youth', 'social'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000', '20000-50000', '>50000'],
ARRAY['All regions'],
'grant', 5000, 50000, 30, 60,
'Projets sportifs fédéraux et associatifs, professionnalisation mouvement sportif. Charente : 5,96M€ 2025.',
'https://www.agencedusport.fr', 'http://www.associations.gouv.fr/le-compte-asso.html', 'annual',
'Associations sportives et fédérations. Projet sportif territorial cohérent. Emplois sportifs.',
'Dossier PST, projet sportif, budget, statuts association, licences fédérales, plan emploi',
true),

-- Agriculture
('PAC MAEC - Mesures Agro-Environnementales', 'Ministère Agriculture / Europe', 'FR', 'National',
ARRAY['agriculture', 'environment', 'biodiversity', 'climate'],
ARRAY['<2000', '2000-5000'],
ARRAY['All regions'],
'grant', 10000, 60000, 50, 80,
'Pratiques agricoles durables : haies, couverts végétaux, prairies, zones humides. Engagement 5 ans.',
'https://www.telepac.agriculture.gouv.fr', 'https://www.telepac.agriculture.gouv.fr', 'annual',
'Exploitations agricoles. Engagement 5 ans. Zones prioritaires PAEC.',
'Formulaire TelePAC MAEC, plan parcellaire, engagement cahier charges, diagnostic exploitation',
true),

('SAFER - Portage Foncier Agricole', 'SAFER Nouvelle-Aquitaine', 'FR', 'National',
ARRAY['agriculture', 'land'],
ARRAY['<2000', '2000-5000'],
ARRAY['Nouvelle-Aquitaine'],
'loan', 50000, 300000, 0, 0,
'Portage foncier temporaire installations agricoles. Achat terrain, portage 3-5 ans, revente agriculteurs.',
'https://safer-na.com', 'https://safer-na.com/services', 'rolling',
'Communes et jeunes agriculteurs. Projet installation agricole viable.',
'Projet installation agricole, business plan, terrain identifié, partenariat SAFER, engagement repreneur',
true),

-- Associations
('FDVA - Fonds Développement Vie Associative', 'DRAJES / Préfecture', 'FR', 'National',
ARRAY['social', 'culture', 'sports', 'youth'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000', '20000-50000', '>50000'],
ARRAY['All regions'],
'grant', 3000, 15000, 50, 80,
'Projets associatifs locaux : formation bénévoles, équipements, innovation sociale. Charente : dépôt Janvier-Mars.',
'https://www.associations.gouv.fr', 'https://www.demarches-simplifiees.fr', 'annual',
'Associations loi 1901. Projet associatif clair. Bénévoles actifs.',
'Formulaire FDVA, projet associatif, budget, statuts, RIB, liste bénévoles, programme formation si FDVA2',
true),

-- Politique de la Ville
('Politique de la Ville - QPV', 'ANCT / Préfecture', 'FR', 'National',
ARRAY['social', 'urban_planning', 'economy', 'education'],
ARRAY['>50000'],
ARRAY['All regions'],
'grant', 30000, 200000, 50, 80,
'Projets Quartiers Prioritaires de la Ville (QPV). Cohésion sociale, emploi, éducation, renouvellement urbain.',
'https://www.anct.gouv.fr', 'https://www.demarches-simplifiees.fr', 'rolling',
'QPV identifié, contrat de ville signé. Projet social/urbain/économique.',
'Projet détaillé QPV, diagnostic social, partenariats, devis, délibération, convention contrat de ville',
true);

-- ============================================
-- NOUVELLE-AQUITAINE REGIONAL PROGRAMS (20)
-- ============================================

INSERT INTO funding_programs (
    name, provider, country, level, eligible_themes, eligible_population_bands, eligible_regions,
    funding_type, amount_min, amount_max, funding_percentage_min, funding_percentage_max,
    description, website_url, application_url, deadline_type, requirements, required_documents, is_active
) VALUES

('Région NA - Monuments Historiques Restauration', 'Région Nouvelle-Aquitaine', 'FR', 'Regional',
ARRAY['heritage', 'culture', 'tourism'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000', '20000-50000', '>50000'],
ARRAY['Nouvelle-Aquitaine'],
'grant', 35000, 400000, 15, 20,
'MH classé (15%) ou inscrit (20%). Seuil minimum 35k€, plafond 400k€. Co-financement DRAC obligatoire, communes/EPCI<150k hab.',
'https://les-aides.nouvelle-aquitaine.fr', 'https://les-aides.nouvelle-aquitaine.fr/culture/restauration-des-monuments-historiques', 'rolling',
'Communes/EPCI <150k hab. MH classé ou inscrit. Co-financement DRAC requis.',
'Formulaire Région NA, arrêté DRAC, devis architecte patrimoine, programme travaux, plan financement global, délibération',
true),

('Région NA - Innovation Territoriale R&D', 'Région Nouvelle-Aquitaine', 'FR', 'Regional',
ARRAY['innovation', 'economy', 'research'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000', '20000-50000', '>50000'],
ARRAY['Nouvelle-Aquitaine'],
'grant', 30000, 150000, 40, 70,
'Soutien innovation et R&D, clusters, pôles compétitivité. Écosystème innovation territorial.',
'https://les-aides.nouvelle-aquitaine.fr', 'https://entreprises.nouvelle-aquitaine.fr', 'rolling',
'Collectivités, EPCI, clusters. Projet innovation R&D territorial. Partenariats recherche.',
'Dossier innovation Région, projet R&D détaillé, budget, partenariats recherche/entreprises, délibération',
true),

('Région NA - Trame Verte et Bleue (TVB)', 'Région Nouvelle-Aquitaine', 'FR', 'Regional',
ARRAY['biodiversity', 'environment', 'land'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000', '20000-50000', '>50000'],
ARRAY['Nouvelle-Aquitaine'],
'grant', 10000, 60000, 40, 70,
'Protection continuités écologiques, corridors biologiques, zones humides. SRCE (Schéma Régional Cohérence Écologique).',
'https://les-aides.nouvelle-aquitaine.fr', 'https://les-aides.nouvelle-aquitaine.fr/environnement', 'rolling',
'Collectivités et EPCI. Projet TVB inscrit SRCE. Diagnostic écologique.',
'Formulaire Région TVB, diagnostic écologique, cartographie continuités, plan gestion, devis, délibération',
true),

('Région NA - Tourisme Durable Innovation', 'Région Nouvelle-Aquitaine', 'FR', 'Regional',
ARRAY['tourism', 'heritage', 'environment', 'innovation'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000', '20000-50000', '>50000'],
ARRAY['Nouvelle-Aquitaine'],
'grant', 20000, 100000, 40, 60,
'Tourisme durable, hébergements éco-responsables, valorisation patrimoine. Innovation offre touristique.',
'https://les-aides.nouvelle-aquitaine.fr', 'https://tourisme-nouvelle-aquitaine.fr', 'annual',
'Collectivités, offices tourisme, EPCI. Projet tourisme durable innovant.',
'Dossier tourisme Région, stratégie territoriale, étude marché/fréquentation, devis, délibération, engagement labels',
true),

('Région NA - Agriculture Circuits Courts', 'Région Nouvelle-Aquitaine', 'FR', 'Regional',
ARRAY['agriculture', 'food', 'economy'],
ARRAY['<2000', '2000-5000', '5000-10000'],
ARRAY['Nouvelle-Aquitaine'],
'grant', 15000, 80000, 40, 70,
'Circuits courts, agriculture biologique, transformation locale, marchés producteurs. PAT. Néo Terra : 30% agriculteurs circuits courts 2030.',
'https://les-aides.nouvelle-aquitaine.fr', 'https://entreprises.nouvelle-aquitaine.fr/actualites/developper-les-circuits-alimentaires-locaux', 'rolling',
'Communes rurales, agriculteurs, EPCI. Projet circuits courts cohérent.',
'Dossier circuits courts Région, business plan agricole, étude marché local, devis, partenariats producteurs, délibération',
true),

('Région NA - Énergies Renouvelables Transition', 'Région Nouvelle-Aquitaine', 'FR', 'Regional',
ARRAY['energy', 'climate', 'environment'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000', '20000-50000', '>50000'],
ARRAY['Nouvelle-Aquitaine'],
'grant', 25000, 150000, 40, 60,
'Production énergies renouvelables : solaire, éolien, méthanisation, bois-énergie. Rénovation énergétique bâtiments publics.',
'https://les-aides.nouvelle-aquitaine.fr', 'https://les-aides.nouvelle-aquitaine.fr/energie', 'rolling',
'Collectivités et EPCI. Projet EnR cohérent PCAET. Audit énergétique.',
'Formulaire Région EnR, audit énergétique, étude technique production, devis, plan financement, délibération',
true),

('Région NA - Mobilités Douces Vélo', 'Région Nouvelle-Aquitaine', 'FR', 'Regional',
ARRAY['mobility', 'environment', 'tourism'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000', '20000-50000', '>50000'],
ARRAY['Nouvelle-Aquitaine'],
'grant', 15000, 80000, 40, 60,
'Aménagements cyclables, voies vertes, véloroutes, bornes vélos électriques. Schéma Régional Véloroutes Voies Vertes.',
'https://les-aides.nouvelle-aquitaine.fr', 'https://les-aides.nouvelle-aquitaine.fr/mobilite', 'rolling',
'Collectivités et EPCI. Projet vélo inscrit schéma régional. Continuité itinéraires.',
'Formulaire vélo Région, plan itinéraires, devis, normes techniques cyclables, délibération, signalétique',
true),

('Région NA - Petites Villes Demain Accompagnement', 'Région Nouvelle-Aquitaine', 'FR', 'Regional',
ARRAY['urban_planning', 'housing', 'commerce'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000'],
ARRAY['Nouvelle-Aquitaine'],
'grant', 50000, 500000, 50, 80,
'Revitalisation petites villes, ingénierie, chef de projet mutualisé. Complément programme national PVD.',
'https://les-aides.nouvelle-aquitaine.fr', 'https://www.anct.gouv.fr/petites-villes-de-demain', 'rolling',
'Communes PVD <20k hab. Convention État/Région signée. Chef projet recruté.',
'Convention PVD, projet détaillé revitalisation, plan financement, délibération, poste chef projet créé',
true),

('Région NA - Aides Investissements Agroalimentaire', 'Région Nouvelle-Aquitaine', 'FR', 'Regional',
ARRAY['agriculture', 'food', 'economy'],
ARRAY['<2000', '2000-5000'],
ARRAY['Nouvelle-Aquitaine'],
'grant', 120000, 3000000, 30, 50,
'Modernisation unités production agroalimentaire, abattage/découpe viandes. Subvention max 500k€.',
'https://les-aides.nouvelle-aquitaine.fr', 'https://entreprises.nouvelle-aquitaine.fr', 'rolling',
'PME agroalimentaires. Projet >120k€. Modernisation outil production.',
'Business plan, devis équipements, étude marché, normes sanitaires, engagement emploi',
true),

('Région NA - Formation Professionnelle Continue', 'Région Nouvelle-Aquitaine', 'FR', 'Regional',
ARRAY['education', 'economy', 'social'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000', '20000-50000', '>50000'],
ARRAY['Nouvelle-Aquitaine'],
'grant', 20000, 100000, 50, 80,
'Formation professionnelle demandeurs emploi, formations qualifiantes métiers en tension.',
'https://les-aides.nouvelle-aquitaine.fr', 'https://www.cap-metiers.fr', 'annual',
'Collectivités, organismes formation, EPCI. Projet formation métiers tension.',
'Programme formation détaillé, public cible, partenariats Pôle Emploi, certification Qualiopi, budget, délibération',
true),

('Région NA - Commerce Proximité Centre-Bourg', 'Région Nouvelle-Aquitaine', 'FR', 'Regional',
ARRAY['commerce', 'economy', 'urban_planning'],
ARRAY['<2000', '2000-5000', '5000-10000'],
ARRAY['Nouvelle-Aquitaine'],
'grant', 5000, 15000, 40, 50,
'Financement investissements TPE commerce et services proximité. Création, développement, reprise.',
'https://les-aides.nouvelle-aquitaine.fr', 'https://entreprises.nouvelle-aquitaine.fr', 'rolling',
'TPE commerce/services. Implantation centre-bourg ou QPV.',
'Business plan commerce, devis investissements, bail ou local propriété, prévisionnel financier 3 ans',
true),

('Région NA - Littoral Durable Plages', 'Région Nouvelle-Aquitaine', 'FR', 'Regional',
ARRAY['environment', 'tourism', 'climate'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000', '20000-50000', '>50000'],
ARRAY['Nouvelle-Aquitaine'],
'grant', 30000, 150000, 25, 40,
'Développement stations balnéaires durables et plages. Prévention érosion, risques climatiques, mobilité décarbonée.',
'https://les-aides.nouvelle-aquitaine.fr', 'https://les-aides.nouvelle-aquitaine.fr/littoral', 'annual',
'Communes littoral NA. Projet station durable. Adaptation climatique.',
'Dossier littoral Région, étude risques côtiers, plan adaptation, devis, stratégie mobilité, délibération',
true),

('Région NA - Projets Vidéoludiques Jeux Vidéo', 'Région Nouvelle-Aquitaine', 'FR', 'Regional',
ARRAY['digital', 'culture', 'innovation'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000', '20000-50000', '>50000'],
ARRAY['Nouvelle-Aquitaine'],
'grant', 30000, 150000, 50, 50,
'Soutien projets jeux vidéo, studios indépendants. Production, développement, innovation gaming.',
'https://les-aides.nouvelle-aquitaine.fr', 'https://entreprises.nouvelle-aquitaine.fr', 'annual',
'Studios jeux vidéo NA. Projet production jeu innovant.',
'Dossier production jeu, prototype/démo, budget détaillé, équipe et CV, business model, partenariats',
true),

('Région NA - Export International PME', 'Région Nouvelle-Aquitaine', 'FR', 'Regional',
ARRAY['economy', 'innovation'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000', '20000-50000', '>50000'],
ARRAY['Nouvelle-Aquitaine'],
'grant', 10000, 20000, 50, 80,
'Soutien export PME <10% CA export. Compétences externes : formation, conseil, marketing international.',
'https://les-aides.nouvelle-aquitaine.fr', 'https://entreprises.nouvelle-aquitaine.fr', 'rolling',
'PME NA <10% CA export. Première démarche export ou développement.',
'Stratégie export, étude marchés cibles, budget action internationale, bilan financier entreprise',
true),

('Région NA - Création Entreprise Innovante', 'Région Nouvelle-Aquitaine', 'FR', 'Regional',
ARRAY['innovation', 'economy', 'digital'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000', '20000-50000', '>50000'],
ARRAY['Nouvelle-Aquitaine'],
'grant', 10000, 20000, 50, 50,
'Aide création entreprise innovante startup. Technologie, modèle économique, usage innovant.',
'https://les-aides.nouvelle-aquitaine.fr', 'https://entreprises.nouvelle-aquitaine.fr', 'rolling',
'Porteurs projet startup NA. Innovation technologique/modèle/usage.',
'Business plan startup, innovation détaillée, CV équipe fondateurs, prévisionnel 3 ans',
true),

('Région NA - Œnotourisme Visites Entreprises', 'Région Nouvelle-Aquitaine', 'FR', 'Regional',
ARRAY['tourism', 'agriculture', 'economy'],
ARRAY['<2000', '2000-5000'],
ARRAY['Nouvelle-Aquitaine'],
'grant', 20000, 100000, 20, 20,
'Œnotourisme, agritourisme, tourisme artisanal. Création/modernisation parcours visite. Taux 20%, plafond 500k€.',
'https://les-aides.nouvelle-aquitaine.fr', 'https://tourisme-nouvelle-aquitaine.fr', 'rolling',
'Exploitations viticoles, fermes, artisans NA. Parcours visite créé/modernisé.',
'Projet œnotouristique, devis aménagements, plan parcours visite, norme ERP, stratégie commercialisation',
true),

('Région NA - Aide Installation Jeunes Agriculteurs (DJA)', 'Région Nouvelle-Aquitaine / Europe', 'FR', 'Regional',
ARRAY['agriculture', 'economy'],
ARRAY['<2000'],
ARRAY['Nouvelle-Aquitaine'],
'grant', 13000, 17000, 100, 100,
'Dotation Jeunes Agriculteurs (DJA). 18-55 ans. Installation chef exploitation. PDE. Complément FEADER possible.',
'https://les-aides.nouvelle-aquitaine.fr', 'https://www.telepac.agriculture.gouv.fr', 'rolling',
'18-55 ans, première installation chef exploitation agricole. Diplôme agricole IV minimum.',
'Formulaire DJA TelePAC, PDE complet, diplômes, prévisionnel économique 5 ans, foncier exploitation',
true),

('Région NA - Foncier Agricole SAFER', 'Région Nouvelle-Aquitaine / SAFER', 'FR', 'Regional',
ARRAY['agriculture', 'land', 'environment'],
ARRAY['<2000'],
ARRAY['Nouvelle-Aquitaine'],
'service', NULL, NULL, NULL, NULL,
'Portage foncier SAFER, acquisitions prioritaires (ENS, PDIPR). Restructuration foncière, préemption terrains agricoles.',
'https://safer-na.com', 'https://safer-na.com', 'permanent',
'Communes et EPCI NA. Projet foncier agricole/naturel. Intérêt général.',
'Convention SAFER, projet foncier détaillé, délibération, zonage ENS/PDIPR si acquisition',
true),

('Région NA - Biodiversité Collèges Ruches', 'Région Nouvelle-Aquitaine', 'FR', 'Regional',
ARRAY['biodiversity', 'education', 'environment'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000', '20000-50000', '>50000'],
ARRAY['Nouvelle-Aquitaine'],
'grant', 1500, 1500, 100, 100,
'Installation ruches dans collèges, sensibilisation biodiversité. Subvention forfaitaire 1 500€.',
'https://les-aides.nouvelle-aquitaine.fr', 'https://les-aides.nouvelle-aquitaine.fr', 'annual',
'Collèges NA. Projet pédagogique biodiversité. Partenariat apiculteur local.',
'Projet pédagogique collège, partenariat apiculteur, autorisation CD, emplacement ruche identifié',
true);

-- ============================================
-- CHARENTE DEPARTMENTAL PROGRAMS (15)
-- ============================================

INSERT INTO funding_programs (
    name, provider, country, level, eligible_themes, eligible_population_bands, eligible_regions,
    funding_type, amount_min, amount_max, funding_percentage_min, funding_percentage_max,
    description, website_url, application_url, deadline_type, requirements, required_documents, is_active
) VALUES

('Département 16 - Équipements Communaux', 'Conseil Départemental Charente', 'FR', 'Departmental',
ARRAY['infrastructure', 'sports', 'culture', 'education'],
ARRAY['<2000', '2000-5000', '5000-10000'],
ARRAY['Charente (16)'],
'grant', 10000, 100000, 25, 40,
'Investissements communaux : écoles, équipements sportifs (gymnases, pistes athlétisme), salles polyvalentes. Priorité communes rurales <5k hab.',
'https://www.lacharente.fr', 'https://portail.citoyen.lacharente.fr', 'annual',
'Communes Charente priorité <5k hab. Équipement structurant communal.',
'Délibération, devis, APD si bâtiment, plan financement, certificats urbanisme, norme accessibilité',
true),

('Département 16 - Patrimoine Monuments Historiques', 'Conseil Départemental Charente', 'FR', 'Departmental',
ARRAY['heritage', 'culture', 'tourism'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000', '20000-50000', '>50000'],
ARRAY['Charente (16)'],
'grant', 10000, 60000, 10, 20,
'20% communes <6k hab, 10% autres. Plafond 300k€/an/propriétaire. Ouverture publique Journées Patrimoine 3 ans.',
'https://www.lacharente.fr', 'https://www.lacharente.fr/vos-services/culture-patrimoine', 'rolling',
'Communes/propriétaires Charente. MH classé ou inscrit. Engagement ouverture publique 3 ans.',
'Délibération, arrêté DRAC, devis architecte patrimoine, programme travaux, engagement ouverture',
true),

('Département 16 - FDAC Voirie Communale', 'Conseil Départemental Charente', 'FR', 'Departmental',
ARRAY['infrastructure', 'mobility'],
ARRAY['<2000', '2000-5000', '5000-10000'],
ARRAY['Charente (16)'],
'grant', 15000, 80000, 20, 35,
'Fonds Départemental Aide Communale (FDAC), entretien voirie communale classée. Forfait 0,8309€/m².',
'https://www.lacharente.fr', 'https://www.lacharente.fr/vos-services/routes', 'annual',
'Communes Charente. Voirie communale classée. Travaux entretien/réfection.',
'Délibération, devis travaux voirie, plan linéaire routes classées, descriptif technique',
true),

('Département 16 - Numérique Rural TPE', 'Conseil Départemental Charente', 'FR', 'Departmental',
ARRAY['digital', 'economy', 'services'],
ARRAY['<2000', '2000-5000'],
ARRAY['Charente (16)'],
'grant', 10000, 50000, 30, 50,
'Déploiement numérique : wifi public, visioconférence, bornes interactives. Réduction fracture numérique rurale.',
'https://www.lacharente.fr', 'https://www.lacharente.fr/vos-services/numerique', 'rolling',
'Communes rurales Charente. Projet numérique collectif. Couverture zones blanches.',
'Projet numérique détaillé, devis équipements, diagnostic couverture, plan formation, délibération',
true),

('Département 16 - Sports Contrat Départemental Animation', 'Conseil Départemental Charente', 'FR', 'Departmental',
ARRAY['sports', 'youth', 'education'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000', '20000-50000', '>50000'],
ARRAY['Charente (16)'],
'grant', 5000, 30000, 50, 50,
'Contrat départemental animation, écoles multisports jeunesse (EMS). Pratique sportive diversifiée.',
'https://www.lacharente.fr', 'https://www.lacharente.fr/vos-services/sports', 'annual',
'Communes et associations Charente. Projet animation sportive jeunesse. Personnel qualifié BPJEPS.',
'Projet sportif, budget, diplômes éducateurs, partenariats clubs, programme activités, délibération',
true),

('Département 16 - Stations Sports Nature', 'Conseil Départemental Charente', 'FR', 'Departmental',
ARRAY['sports', 'tourism', 'environment'],
ARRAY['<2000', '2000-5000', '5000-10000'],
ARRAY['Charente (16)'],
'grant', 10000, 50000, 30, 50,
'Réseau stations sports nature labellisées. Randonnée, vélo, canoë, escalade. Tourisme sportif nature.',
'https://www.lacharente.fr', 'https://www.lacharente.fr/vos-services/sports', 'rolling',
'Communes et EPCI Charente. Site naturel potentiel sports nature. Labellisation station possible.',
'Projet station sports nature, diagnostic site, activités identifiées, signalétique, plan gestion, délibération',
true),

('Département 16 - Manifestations Historiques Patrimoine', 'Conseil Départemental Charente', 'FR', 'Departmental',
ARRAY['heritage', 'culture', 'tourism'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000', '20000-50000', '>50000'],
ARRAY['Charente (16)'],
'grant', 5000, 15000, 30, 50,
'Manifestations historiques, patrimoine, archéologie. Reconstitutions historiques, métiers patrimoine.',
'https://www.lacharente.fr', 'https://www.lacharente.fr/vos-services/culture', 'annual',
'Communes et associations Charente. Manifestation historique/patrimoniale. Public >500 personnes.',
'Programme manifestation, budget détaillé, partenariats scientifiques, communication, assurances, délibération',
true),

('Département 16 - Recherche Archéologie Histoire', 'Conseil Départemental Charente', 'FR', 'Departmental',
ARRAY['research', 'heritage', 'culture'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000', '20000-50000', '>50000'],
ARRAY['Charente (16)'],
'grant', 3000, 20000, 40, 60,
'Recherche archéologique, historique, paléontologique. Fouilles programmées, programmes collectifs recherche.',
'https://www.lacharente.fr', 'https://www.lacharente.fr/vos-services/culture', 'annual',
'Chercheurs, associations, communes Charente. Recherche scientifique patrimoine. Autorisation DRAC.',
'Programme scientifique recherche, CV chercheurs, autorisation DRAC fouilles, budget, valorisation prévue',
true),

('Département 16 - Itinéraires Randonnée PDIPR', 'Conseil Départemental Charente', 'FR', 'Departmental',
ARRAY['tourism', 'environment', 'land'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000', '20000-50000', '>50000'],
ARRAY['Charente (16)'],
'grant', 5000, 30000, 40, 60,
'Plan Départemental Itinéraires Promenade Randonnée (PDIPR). Acquisitions foncières chemins ruraux.',
'https://www.lacharente.fr', 'https://www.lacharente.fr/vos-services/tourisme', 'rolling',
'Communes Charente. Itinéraire randonnée inscrit ou inscription PDIPR. Balisage FFRandonnée.',
'Plan itinéraire randonnée, parcelles foncier, balisage FFRandonnée, convention passage, délibération',
true),

('Département 16 - Haies Bocagères Biodiversité', 'Conseil Départemental Charente', 'FR', 'Departmental',
ARRAY['biodiversity', 'agriculture', 'environment', 'climate'],
ARRAY['<2000', '2000-5000'],
ARRAY['Charente (16)'],
'grant', 5000, 25000, 50, 70,
'Reconstitution haies bocagères cohérentes. Protection érosion sols, biodiversité. Essences locales.',
'https://www.lacharente.fr', 'https://www.lacharente.fr/vos-services/environnement', 'rolling',
'Communes et agriculteurs Charente. Projet haies cohérent territoire. Essences locales. Gestion durable 15 ans.',
'Plan plantation haies cohérent, essences locales, gestion durable 15 ans, devis, cartographie, délibération',
true),

('Département 16 - Effacement Réseaux Aériens', 'Conseil Départemental Charente', 'FR', 'Departmental',
ARRAY['infrastructure', 'heritage', 'urban_planning'],
ARRAY['<2000', '2000-5000', '5000-10000'],
ARRAY['Charente (16)'],
'grant', 20000, 100000, 25, 40,
'Effacement réseaux électriques et télécom aériens. Amélioration cadre de vie, valorisation patrimoine.',
'https://www.lacharente.fr', 'https://www.lacharente.fr', 'rolling',
'Communes Charente. Effacement réseaux aériens centre-bourg ou entrée village. Convention Enedis/Orange.',
'Convention Enedis/Orange, plan effacement réseaux, devis, délibération, coordination travaux voirie',
true),

('Département 16 - Collèges Restauration Bio Local', 'Conseil Départemental Charente', 'FR', 'Departmental',
ARRAY['food', 'agriculture', 'education'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000', '20000-50000', '>50000'],
ARRAY['Charente (16)'],
'grant', 1000, 3000, 100, 100,
'Achat produits locaux collèges via plateforme Agrilocal. Circuits courts restauration collective.',
'https://www.lacharente.fr', 'https://www.agrilocal16.fr', 'rolling',
'Collèges Charente. Approvisionnement local via Agrilocal. Partenariat producteurs locaux.',
'Projet approvisionnement local, convention Agrilocal, producteurs identifiés, projet pédagogique',
true),

('Département 16 - Aménagements Fonciers AFAFE', 'Conseil Départemental Charente', 'FR', 'Departmental',
ARRAY['agriculture', 'land', 'environment'],
ARRAY['<2000'],
ARRAY['Charente (16)'],
'grant', 50000, 300000, 30, 50,
'Aménagement Foncier Agricole Forestier Environnemental (AFAFE). Gestion haies, chemins, restructuration foncière.',
'https://www.lacharente.fr', 'https://www.lacharente.fr', 'rolling',
'Communes rurales Charente. Périmètre AFAFE défini. Commission AFAFE. Enquête publique.',
'Périmètre AFAFE, commission constituée, plan aménagement détaillé, enquête publique, délibération',
true),

('Département 16 - Habitat Partagé Inclusif', 'Conseil Départemental Charente', 'FR', 'Departmental',
ARRAY['housing', 'social', 'health'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000', '20000-50000', '>50000'],
ARRAY['Charente (16)'],
'grant', 20000, 80000, 30, 50,
'Habitat partagé/inclusif, regroupement résidents. Logement adapté perte autonomie. Alternative EHPAD.',
'https://www.lacharente.fr', 'https://www.lacharente.fr/vos-services/solidarite', 'rolling',
'Communes et associations Charente. Projet habitat partagé/inclusif. Capacité 6-12 résidents.',
'Projet habitat détaillé, capacité résidents, personnel, accessibilité, convention ARS si médico-social, délibération',
true),

('Département 16 - Protection Animale Refuges', 'Conseil Départemental Charente', 'FR', 'Departmental',
ARRAY['social', 'environment'],
ARRAY['<2000', '2000-5000', '5000-10000', '10000-20000', '20000-50000', '>50000'],
ARRAY['Charente (16)'],
'grant', 5000, 20000, 40, 60,
'Soutien protection animale, refuges, campagnes stérilisation. Bien-être animal.',
'https://www.lacharente.fr', 'https://www.lacharente.fr', 'annual',
'Associations protection animale Charente. Refuge agréé ou projet agrément. Vétérinaire partenaire.',
'Projet association, budget, refuge agréé/démarche agrément, capacité accueil, partenariat vétérinaire',
true);

-- ============================================
-- COMMUNAUTÉ DE COMMUNES PROGRAMS (8)
-- ============================================

INSERT INTO funding_programs (
    name, provider, country, level, eligible_themes, eligible_population_bands, eligible_regions,
    funding_type, amount_min, amount_max, funding_percentage_min, funding_percentage_max,
    description, website_url, application_url, deadline_type, requirements, required_documents, is_active
) VALUES

('CC Cœur de Charente - Coup de Pouce Entreprises', 'Communauté Communes Cœur Charente', 'FR', 'Intercommunal',
ARRAY['economy', 'commerce', 'services'],
ARRAY['<2000', '2000-5000'],
ARRAY['Charente (16)'],
'grant', 3000, 25000, 20, 20,
'Création, cession-reprise, développement TPE. Subvention 20% plafonnée 5k€. Cœur de Charente.',
'https://les-aides.fr', 'https://les-aides.fr/aide/Zjl_3w/cc-coeur-de-charente/coup-de-pouce-coeur-de-charente.html', 'rolling',
'TPE territoire Cœur Charente. Création/reprise/développement. Investissement >3k€ HT.',
'Business plan, devis investissements, prévisionnel 3 ans, immatriculation, statuts, RIB',
true),

('CC Cœur de Charente - OPAH Rénovation Habitat', 'CC Cœur Charente / ANAH', 'FR', 'Intercommunal',
ARRAY['housing', 'energy', 'urban_planning'],
ARRAY['<2000', '2000-5000'],
ARRAY['Charente (16)'],
'grant', 40000, 70000, 60, 80,
'OPAH. Travaux énergétiques selon saut classe DPE (2-4 classes). Accompagnement Soliha 16.',
'https://soliha16.fr', 'https://soliha16.fr/opah-coeur-de-charente/', 'rolling',
'Propriétaires occupants Cœur Charente conditions ressources ANAH. Gain énergétique 2-4 classes DPE.',
'Dossier ANAH via Soliha, diagnostic énergétique, devis travaux, conditions ressources, engagement occupation 6 ans',
true),

('CC Charente Limousine - Coup de Pouce TPE', 'Communauté Communes Charente Limousine', 'FR', 'Intercommunal',
ARRAY['economy', 'commerce', 'environment'],
ARRAY['<2000'],
ARRAY['Charente (16)'],
'grant', 3000, 4500, 30, 40,
'TPE commerce/services. Transitions RSE, circuits courts, économie circulaire. Bonus centralités.',
'https://mesaidespubliques.infogreffe.fr', 'https://mesaidespubliques.infogreffe.fr/aides/nouvelle-aquitaine-coup-de-pouce-tpe', 'rolling',
'TPE Charente Limousine. Commerce/services proximité. Transitions RSE/circuits courts.',
'Business plan, devis, approche RSE/circuits courts, implantation centralité justifiée, prévisionnel',
true),

('CC Générique - Développement Local Villages', 'Communauté de Communes', 'FR', 'Intercommunal',
ARRAY['infrastructure', 'culture', 'social', 'economy'],
ARRAY['<2000', '2000-5000'],
ARRAY['All regions'],
'grant', 5000, 30000, 20, 40,
'Projets locaux communes membres, associations locales. Soutien vie locale intercommunale.',
'https://www.lacharente.fr', NULL, 'rolling',
'Communes membres CC ou associations locales. Projet local bénéfice territorial.',
'Projet détaillé, budget, délibération commune, partenariats, co-financement commune justifié',
true),

('CC Générique - Services Mutualisés', 'Communauté de Communes', 'FR', 'Intercommunal',
ARRAY['services', 'digital', 'infrastructure'],
ARRAY['<2000', '2000-5000'],
ARRAY['All regions'],
'grant', 10000, 50000, 30, 50,
'Mutualisation services : secrétariat, informatique, technique, RH. Économies échelle.',
'https://www.lacharente.fr', NULL, 'rolling',
'Communes membres CC. Service mutualisé intercommunal. Convention services.',
'Convention mutualisation, projet service mutualisé, budget, économies estimées, délibérations communes',
true),

('CC Générique - Tourisme Intercommunal', 'Communauté de Communes', 'FR', 'Intercommunal',
ARRAY['tourism', 'heritage', 'economy'],
ARRAY['<2000', '2000-5000'],
ARRAY['All regions'],
'grant', 10000, 50000, 30, 50,
'Développement tourisme intercommunal, signalétique, parcours, valorisation patrimoine.',
'https://www.lacharente.fr', NULL, 'rolling',
'Communes membres CC ou office tourisme. Projet tourisme intercommunal. Signalétique cohérente.',
'Schéma touristique intercommunal, signalétique, parcours identifiés, budget, délibérations',
true),

('CC Générique - Environnement Transition', 'Communauté de Communes', 'FR', 'Intercommunal',
ARRAY['environment', 'energy', 'waste', 'climate'],
ARRAY['<2000', '2000-5000', '5000-10000'],
ARRAY['All regions'],
'grant', 15000, 80000, 40, 60,
'Projets environnementaux intercommunaux, déchetteries, compostage, énergies renouvelables. PCAET.',
'https://www.lacharente.fr', NULL, 'rolling',
'Communes membres CC. Projet environnement intercommunal. PCAET si applicable.',
'PCAET ou projet environnement, budget, délibérations communes, service environnement CC',
true),

('CC Générique - Zones Revitalisation Rurale (ZRR)', 'État / Communauté de Communes', 'FR', 'Intercommunal',
ARRAY['economy', 'commerce', 'services'],
ARRAY['<2000', '2000-5000'],
ARRAY['All regions'],
'tax_exemption', NULL, NULL, NULL, NULL,
'Zone Revitalisation Rurale (ZRR). Exonérations fiscales entreprises : CFE 2 ans, cotisations sociales.',
'https://www.lacharente.fr', NULL, 'permanent',
'Entreprises implantées commune ZRR. Création ou reprise <50 salariés.',
'Implantation commune ZRR, création/reprise entreprise, déclaration fiscale',
true);

-- ============================================
-- VERIFICATION
-- ============================================

-- Count by level
SELECT level, COUNT(*) as count 
FROM funding_programs 
GROUP BY level 
ORDER BY count DESC;

-- ============================================
-- END OF IMPORT
-- ============================================
